licenses(["notice"])  # Apache 2.0

package(
    default_visibility = [
         "//visibility:public",
    ],
)

native.py_library(
    name = "core",
    srcs = ["__init__.py"],
    deps = [
        "//parallax/core/python:python"
    ],
)